# This is a basic workflow to help you get started with Actions

name: Add Tag

# Controls when the workflow will run
on:
  # Triggers the workflow on push
  push:
    branches: ["*"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: add tag
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Create/Update tag
      # You may pin to the exact commit or the version.
      # uses: rickstaa/action-create-tag@ded737969d700db255f52e23947cccc3bf8336d7
        uses: rickstaa/action-create-tag@v.1.3.2
        with:
          # GITHUB_TOKEN. Optional if you use checkout@v2 action.
          github_token: ${{ secrets.GITHUB_TOKEN }} # default is ${{ github.token }}
          # Tag you want to create or update.
          tag: "Latest" 
          # Tag message.
          message: "Latest Release"
          # The commit SHA hash on which you want to push the tag. Uses latest commit by default.
          # commit_sha: # optional
          # Optional. Force push the tag. Defaults to 'false'.
          force_push_tag: false # default is false
