# This is a basic workflow to help you get started with Actions

name: Add Tag

# Controls when the workflow will run
on:
  # Triggers the workflow on push
  push:
    branches: ["*"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: add tag
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # rickstaa's tagger repo (rickstaa/action-create-tag) 
    # has fatal error: "not in a git repository"
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # auto tag
    - name: Github auto tagger
      uses: VegetableGarden/beet@0.0.3
      with:
        # The tag major version
        major-version: 0 # optional, default is 0
        # The tag minor version
        minor-version: 1 # optional, default is 0
